
CREATE TABLE HR.COUNTRIES 
(
  COUNTRY_ID CHAR(2 BYTE) NOT NULL 
, COUNTRY_NAME VARCHAR2(40 BYTE) 
, REGION_ID NUMBER 
, CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY 
  (
    COUNTRY_ID 
  )
  ENABLE 
) 
ORGANIZATION INDEX 
PCTTHRESHOLD 50;

CREATE TABLE HR.DEPARTMENTS 
(
  DEPARTMENT_ID NUMBER(4, 0) NOT NULL 
, DEPARTMENT_NAME VARCHAR2(30 BYTE) NOT NULL 
, MANAGER_ID NUMBER(6, 0) 
, LOCATION_ID NUMBER(4, 0) 
);

CREATE TABLE HR.EMPLOYEES 
(
  EMPLOYEE_ID NUMBER(6, 0) NOT NULL 
, FIRST_NAME VARCHAR2(20 BYTE) 
, LAST_NAME VARCHAR2(25 BYTE) NOT NULL 
, EMAIL VARCHAR2(25 BYTE) NOT NULL 
, PHONE_NUMBER VARCHAR2(20 BYTE) 
, HIRE_DATE DATE NOT NULL 
, JOB_ID VARCHAR2(10 BYTE) NOT NULL 
, SALARY NUMBER(8, 2) 
, COMMISSION_PCT NUMBER(2, 2) 
, MANAGER_ID NUMBER(6, 0) 
, DEPARTMENT_ID NUMBER(4, 0) 
);

CREATE TABLE HR.JOBS 
(
  JOB_ID VARCHAR2(10 BYTE) NOT NULL 
, JOB_TITLE VARCHAR2(35 BYTE) NOT NULL 
, MIN_SALARY NUMBER(6, 0) 
, MAX_SALARY NUMBER(6, 0) 
);

CREATE TABLE HR.JOB_HISTORY 
(
  EMPLOYEE_ID NUMBER(6, 0) NOT NULL 
, START_DATE DATE NOT NULL 
, END_DATE DATE NOT NULL 
, JOB_ID VARCHAR2(10 BYTE) NOT NULL 
, DEPARTMENT_ID NUMBER(4, 0) 
);

CREATE TABLE HR.LOCATIONS 
(
  LOCATION_ID NUMBER(4, 0) NOT NULL 
, STREET_ADDRESS VARCHAR2(40 BYTE) 
, POSTAL_CODE VARCHAR2(12 BYTE) 
, CITY VARCHAR2(30 BYTE) NOT NULL 
, STATE_PROVINCE VARCHAR2(25 BYTE) 
, COUNTRY_ID CHAR(2 BYTE) 
);

CREATE TABLE HR.REGIONS 
(
  REGION_ID NUMBER NOT NULL 
, REGION_NAME VARCHAR2(25 BYTE) 
);

