package com.cdyne.ws.weatherws;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

public class WeatherSoap12Client
{
  @WebServiceRef
  private static Weather weather;

  public static void main(String [] args)
  {
    weather = new Weather();
    WeatherSoap weatherSoap = weather.getWeatherSoap12();
    // Add your code to call the desired methods.
  }
}
