package com.cdyne.ws.weatherws;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL",
  targetNamespace="http://ws.cdyne.com/WeatherWS/", name="Weather")
public class Weather
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.cdyne.ws.weatherws.Weather");
      URL baseUrl = Weather.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            Weather.class.getResource("http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL",
          e);
    }
  }

  public Weather()
  {
    super(wsdlLocationURL,
          new QName("http://ws.cdyne.com/WeatherWS/", "Weather"));
  }

  public Weather(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="WeatherSoap12")
  public com.cdyne.ws.weatherws.WeatherSoap getWeatherSoap12()
  {
    return (com.cdyne.ws.weatherws.WeatherSoap) super.getPort(new QName("http://ws.cdyne.com/WeatherWS/",
                                                                        "WeatherSoap12"),
                                                              com.cdyne.ws.weatherws.WeatherSoap.class);
  }

  @WebEndpoint(name="WeatherSoap12")
  public com.cdyne.ws.weatherws.WeatherSoap getWeatherSoap12(WebServiceFeature... features)
  {
    return (com.cdyne.ws.weatherws.WeatherSoap) super.getPort(new QName("http://ws.cdyne.com/WeatherWS/",
                                                                        "WeatherSoap12"),
                                                              com.cdyne.ws.weatherws.WeatherSoap.class,
                                                              features);
  }

  @WebEndpoint(name="WeatherSoap")
  public com.cdyne.ws.weatherws.WeatherSoap getWeatherSoap()
  {
    return (com.cdyne.ws.weatherws.WeatherSoap) super.getPort(new QName("http://ws.cdyne.com/WeatherWS/",
                                                                        "WeatherSoap"),
                                                              com.cdyne.ws.weatherws.WeatherSoap.class);
  }

  @WebEndpoint(name="WeatherSoap")
  public com.cdyne.ws.weatherws.WeatherSoap getWeatherSoap(WebServiceFeature... features)
  {
    return (com.cdyne.ws.weatherws.WeatherSoap) super.getPort(new QName("http://ws.cdyne.com/WeatherWS/",
                                                                        "WeatherSoap"),
                                                              com.cdyne.ws.weatherws.WeatherSoap.class,
                                                              features);
  }
}
