package com.cdyne.ws.weatherws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL",
  targetNamespace="http://ws.cdyne.com/WeatherWS/", name="WeatherSoap")
@XmlSeeAlso(
  { com.cdyne.ws.weatherws.ObjectFactory.class })
public interface WeatherSoap
{
  @WebMethod(operationName="GetWeatherInformation", action="http://ws.cdyne.com/WeatherWS/GetWeatherInformation")
  @Action(input="http://ws.cdyne.com/WeatherWS/GetWeatherInformation",
    output="http://ws.cdyne.com/WeatherWS/WeatherSoap/GetWeatherInformationResponse")
  @ResponseWrapper(localName="GetWeatherInformationResponse",
    targetNamespace="http://ws.cdyne.com/WeatherWS/", className="com.cdyne.ws.weatherws.GetWeatherInformationResponse")
  @RequestWrapper(localName="GetWeatherInformation", targetNamespace="http://ws.cdyne.com/WeatherWS/",
    className="com.cdyne.ws.weatherws.GetWeatherInformation")
  @WebResult(targetNamespace="http://ws.cdyne.com/WeatherWS/", name="GetWeatherInformationResult")
  public com.cdyne.ws.weatherws.ArrayOfWeatherDescription getWeatherInformation();

  @WebMethod(operationName="GetCityForecastByZIP", action="http://ws.cdyne.com/WeatherWS/GetCityForecastByZIP")
  @Action(input="http://ws.cdyne.com/WeatherWS/GetCityForecastByZIP",
    output="http://ws.cdyne.com/WeatherWS/WeatherSoap/GetCityForecastByZIPResponse")
  @ResponseWrapper(localName="GetCityForecastByZIPResponse",
    targetNamespace="http://ws.cdyne.com/WeatherWS/", className="com.cdyne.ws.weatherws.GetCityForecastByZIPResponse")
  @RequestWrapper(localName="GetCityForecastByZIP", targetNamespace="http://ws.cdyne.com/WeatherWS/",
    className="com.cdyne.ws.weatherws.GetCityForecastByZIP")
  @WebResult(targetNamespace="http://ws.cdyne.com/WeatherWS/", name="GetCityForecastByZIPResult")
  public com.cdyne.ws.weatherws.ForecastReturn getCityForecastByZIP(@WebParam(targetNamespace="http://ws.cdyne.com/WeatherWS/",
      name="ZIP")
    String zip);

  @WebMethod(operationName="GetCityWeatherByZIP", action="http://ws.cdyne.com/WeatherWS/GetCityWeatherByZIP")
  @Action(input="http://ws.cdyne.com/WeatherWS/GetCityWeatherByZIP",
    output="http://ws.cdyne.com/WeatherWS/WeatherSoap/GetCityWeatherByZIPResponse")
  @ResponseWrapper(localName="GetCityWeatherByZIPResponse",
    targetNamespace="http://ws.cdyne.com/WeatherWS/", className="com.cdyne.ws.weatherws.GetCityWeatherByZIPResponse")
  @RequestWrapper(localName="GetCityWeatherByZIP", targetNamespace="http://ws.cdyne.com/WeatherWS/",
    className="com.cdyne.ws.weatherws.GetCityWeatherByZIP")
  @WebResult(targetNamespace="http://ws.cdyne.com/WeatherWS/", name="GetCityWeatherByZIPResult")
  public com.cdyne.ws.weatherws.WeatherReturn getCityWeatherByZIP(@WebParam(targetNamespace="http://ws.cdyne.com/WeatherWS/",
      name="ZIP")
    String zip);
}
